In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
my_li=[1,2,3,4]
my_tu=(1,3,5,6)


In [4]:
my_li[-1]=5
print(my_li)

[1, 2, 3, 5]


In [7]:
a=[23,14,23,25,14]

b=set(a)
b=list(b)
print(b)

[25, 14, 23]


In [8]:
my_dict = {'a':1, 'a':2}
print(my_dict)

{'a': 2}


In [9]:
my_di={'a':1,'b':2,'c':3,'d':4}
for x in my_di:
    print(x)

a
b
c
d


In [11]:
for key,value in my_di.items():
    print(key,value)
    

a 1
b 2
c 3
d 4


In [12]:
my_list = [23,34,534,12]
for index, value in enumerate(my_list):
    print(index, value)

0 23
1 34
2 534
3 12


# numpy


In [13]:
my_list=[1,4,56,7,89,44,90]

In [16]:
a=np.array(my_list)

In [17]:
my_ca=[3,5,88,90,22,41,21]
b=np.array(my_ca)

In [18]:
print(a+b)

[  4   9 144  97 111  85 111]


In [19]:
print(a*b)


[   3   20 4928  630 1958 1804 1890]


In [20]:
a=[[1,2,3],
  [4,5,6]]
a=np.array(a)



In [21]:
print(a)

[[1 2 3]
 [4 5 6]]


In [22]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
a.reshape(1,6) #or a.ravel()

array([[1, 2, 3, 4, 5, 6]])

# pandas


In [26]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['NYC', 'LA', 'Chicago']
}

In [28]:
df = pd.DataFrame(data)

print(df)

      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago


In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes


In [31]:
df.shape

(3, 3)

In [34]:
df[df['Age']>=30]['Name']

1        Bob
2    Charlie
Name: Name, dtype: object

# BÀI TẬP PYTHON



In [5]:
# Tìm tất cả các số nguyên tố nhỏ hơn 100.

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True
n=100
# Tạo danh sách các số nguyên tố nhỏ hơn n
primes = []  # Khởi tạo danh sách rỗng để lưu số nguyên tố
for i in range(n):
    if is_prime(i):
        primes.append(i)

# In danh sách các số nguyên tố ra màn hình
print("Các số nguyên tố nhỏ hơn", n, "là:")
print(primes)


Các số nguyên tố nhỏ hơn 100 là:
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [8]:
# kiểm tra số nguyên tố:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True
is_prime(92)


False

In [10]:
# tính giao thừa số nguyên dương
def giaithua(n):
    if n==0 or n==1:
        return 1
    else:
        return n*giaithua(n-1)
giaithua(3)

6

In [11]:
#Viết hàm kiểm tra chuỗi có phải là palindrome không.
def is_palindrome(s):
    s=s.lower().replace(" ","")
    if s==s[::-1]:
        return True
    else:
        return False
is_palindrome("hello")
    

False

In [16]:
#Viết chương trình đếm số lần xuất hiện của từng phần tử trong một danh sách
def count(my_list):
    dic={}
    for i in my_list:
        if i in dic:
            dic[i]+=1
        else:
            dic[i]=1
    return dic
count(['apple', 'banana', 'apple'])




{'apple': 2, 'banana': 1}

In [18]:
#Viết hàm nhận vào danh sách số, trả về danh sách chứa các số chia hết cho 3.
def div_3(my_list):
    my_li=[]
    for x in my_list:
        if x%3 ==0:
            my_li.append(x)
        else:
            continue
    print(my_li)
div_3([2,3,6,9,10])

[3, 6, 9]


In [21]:
# Viết chương trình đếm số lần xuất hiện của từng ký tự trong một chuỗi.
def count_ele(my_str):
    dic={}
    for x in my_str:
        if x in dic:
            dic[x]+=1
        else:
            dic[x]=1
    print(dic)
count_ele("I AM A BOY")

{'I': 1, ' ': 3, 'A': 2, 'M': 1, 'B': 1, 'O': 1, 'Y': 1}


In [26]:
#Cho danh sách tên học sinh, đếm xem có bao nhiêu tên khác nhau.
def su_name(li_name):
    a=set(li_name)
    b=list(a)
    print(len(a))
    print(a)
su_name(["LINH","HUNG","LINH","MY"])

3
{'MY', 'LINH', 'HUNG'}


# BÀI TẬP NUMPY


In [31]:
import numpy as np
a=np.random.randint(0,9,(1,9))
print(a)

[[3 7 3 8 8 7 2 1 7]]


In [34]:
arr = np.arange(10)
print(arr) 
b=np.sum(arr)
c=np.mean(arr)
min_arr=np.min(arr)
max_arr=np.max(arr)
print(b,c,min_arr,max_arr)

[0 1 2 3 4 5 6 7 8 9]
45 4.5 0 9


In [40]:

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])
print(a[:,1])
print(a[3,:])

[ 2  5  8 11]
[10 11 12]


In [2]:
import numpy as np
a = np.array([[5, 12, 7],
              [20, 3, 15],
              [8, 25, 1]])

# Trích xuất các phần tử > 10
result = a[a > 10]

print(result)

[12 20 15 25]


In [3]:
#Tạo 2 mảng ngẫu nhiên cùng kích thước, thực hiện cộng, trừ, nhân từng phần tử.
#Tính phương sai, độ lệch chuẩn và trung vị của một mảng ngẫu nhiên.
#TChuẩn hóa một mảng dữ liệu (z-score).
import numpy as np

# Tạo 2 mảng ngẫu nhiên 3x3
a = np.random.randint(1, 10, size=(3, 3))
b = np.random.randint(1, 10, size=(3, 3))

print(a)
print(b)

# Cộng từng phần tử
add = a + b
print(add)

# Trừ từng phần tử
sub = a - b
print(sub)

# Nhân từng phần tử (element-wise)
mul = a * b
print(mul)



[[9 9 8]
 [2 2 3]
 [8 9 7]]
[[8 3 8]
 [1 8 2]
 [4 2 5]]
[[17 12 16]
 [ 3 10  5]
 [12 11 12]]
[[ 1  6  0]
 [ 1 -6  1]
 [ 4  7  2]]
[[72 27 64]
 [ 2 16  6]
 [32 18 35]]


In [6]:
import numpy as np

# Tạo mảng ngẫu nhiên
data = np.random.randint(1, 100, size=20)

print(data)

# Phương sai
variance = np.var(data)
print("Phương sai:", variance)

# Độ lệch chuẩn
std_dev = np.std(data)
print("Độ lệch chuẩn:", std_dev)

# Trung vị
median = np.median(data)
print("Trung vị:", median)

# Tính trung bình và độ lệch chuẩn
mean = np.mean(data)
std = np.std(data)

# Chuẩn hóa Z-score
z_scores = (data - mean) / std

print("Z-score:", z_scores)




[90 18 10 78  3 24 33 19 39 16 98  9 37 74 82  9 61 59 79 81]
Phương sai: 976.5475
Độ lệch chuẩn: 31.249759999078393
Trung vị: 38.0
Z-score: [ 1.40961083 -0.89440687 -1.15040884  1.02560788 -1.37441056 -0.70240539
 -0.41440318 -0.86240662 -0.22240171 -0.95840736  1.66561279 -1.18240908
 -0.2864022   0.89760689  1.15360886 -1.18240908  0.4816037   0.41760321
  1.05760812  1.12160861]


# BÀI TẬP PANDAS

In [27]:
# import file
import pandas as pd
df = pd.read_csv('/Users/manhhung/Downloads/spotify_top_1000_tracks.csv')
df.head(10)


track_name                artist  \
0         All The Stars (with SZA)        Kendrick Lamar   
1                          Starboy            The Weeknd   
2                         Señorita          Shawn Mendes   
3                       Heat Waves         Glass Animals   
4                  Let Me Love You              DJ Snake   
5                         La La La           Naughty Boy   
6                       Apocalypse  Cigarettes After Sex   
7                     Good For You          Selena Gomez   
8                             Baby         Justin Bieber   
9  There's Nothing Holdin' Me Back          Shawn Mendes   

                                               album release_date  popularity  \
0  Black Panther The Album Music From And Inspire...   2018-02-09          95   
1                                            Starboy   2016-11-25          90   
2                                           Señorita   2019-06-21          80   
3                                          Dreamland   2020-08-07          87   
4                                             Encore   2016-08-05          87   
5                                           La La La   2013-01-01          77   
6                               Cigarettes After Sex   2017-06-09          73   
7                                   Revival (Deluxe)   2015-10-09          80   
8                                       My World 2.0   2010-01-01          84   
9                                Illuminate (Deluxe)   2017-04-20          88   

                                         spotify_url                      id  \
0  https://open.spotify.com/track/3GCdLUSnKSMJhs4...  3GCdLUSnKSMJhs4Tj6CV3s   
1  https://open.spotify.com/track/7MXVkk9YMctZqd1...  7MXVkk9YMctZqd1Srtv4MB   
2  https://open.spotify.com/track/0TK2YIli7K1leLo...  0TK2YIli7K1leLovkQiNik   
3  https://open.spotify.com/track/3USxtqRwSYz57Ew...  3USxtqRwSYz57Ewm6wWRMp   
4  https://open.spotify.com/track/0lYBSQXN6rCTvUZ...  0lYBSQXN6rCTvUZvg9S0lU   
5  https://open.spotify.com/track/52gvlDnre9craz9...  52gvlDnre9craz9dKGObp8   
6  https://open.spotify.com/track/0yc6Gst2xkRu0eM...  0yc6Gst2xkRu0eMLeRMGCX   
7  https://open.spotify.com/track/5xdVqHtFS0eLuNp...  5xdVqHtFS0eLuNp4Z8Wbpa   
8  https://open.spotify.com/track/6epn3r7S14KUqlR...  6epn3r7S14KUqlReYr77hA   
9  https://open.spotify.com/track/7JJmb5XwzOO8jgp...  7JJmb5XwzOO8jgpou264Ml   

   duration_min  
0      3.869767  
1      3.840883  
2      3.182667  
3      3.980083  
4      3.432433  
5      3.679650  
6      4.843600  
7      3.688000  
8      3.570667  
9      3.324000

In [16]:
df.describe()

popularity  duration_min
count  1000.000000   1000.000000
mean     56.669000      3.318516
std      28.192805      0.849591
min       0.000000      0.969150
25%      37.000000      2.754021
50%      68.000000      3.293833
75%      79.000000      3.745721
max      97.000000      9.497883

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   track_name    1000 non-null   object 
 1   artist        1000 non-null   object 
 2   album         1000 non-null   object 
 3   release_date  1000 non-null   object 
 4   popularity    1000 non-null   int64  
 5   spotify_url   1000 non-null   object 
 6   id            1000 non-null   object 
 7   duration_min  1000 non-null   float64
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB


In [20]:
rows,cols=df.shape

In [22]:
df.dtypes

track_name       object
artist           object
album            object
release_date     object
popularity        int64
spotify_url      object
id               object
duration_min    float64
dtype: object

In [23]:
df.isnull().sum()

track_name      0
artist          0
album           0
release_date    0
popularity      0
spotify_url     0
id              0
duration_min    0
dtype: int64

In [30]:
justin_songs=df[df['artist']=='Justin Bieber']['track_name']
print(justin_songs)

8                                        Baby
18                                      Sorry
45                                      Ghost
57                              Love Yourself
307                                Intentions
327    Peaches (feat. Daniel Caesar & Giveon)
329                                   Purpose
562                             Favorite Girl
563                                 Boyfriend
564                                   Love Me
565                         What Do You Mean?
Name: track_name, dtype: object


In [31]:
songs_4=df[df['duration_min']>4]['track_name']
print(songs_4)

6                                     Apocalypse
11                           Love Me Like You Do
12                            Summertime Sadness
19                                   Die For You
21                                   Mockingbird
                         ...                    
792                                          Her
793                   Purity (feat. Frank Ocean)
795    Don’t Matter To Me (with Michael Jackson)
798                                     Novacane
799                                  The Morning
Name: track_name, Length: 155, dtype: object


In [32]:
songs_4=df[df['popularity']>80]['track_name']
print(songs_4)

0         All The Stars (with SZA)
1                          Starboy
3                       Heat Waves
4                  Let Me Love You
8                             Baby
                  ...             
813         Thank You (Not So Bad)
815             I Don't Wanna Wait
819                   Stumblin' In
821       MONTAGEM TOMADA - Slowed
822    I Adore You (feat. Daecolm)
Name: track_name, Length: 201, dtype: object


In [36]:
df['release_date']=pd.to_datetime(df['release_date'],errors='coerce')
before_2010=df[df['release_date']<'2010-01-01']['track_name']
print(before_2010)


21                                         Mockingbird
33                                          Without Me
60                  Hips Don't Lie (feat. Wyclef Jean)
61                                         Summer Love
63     What Goes Around.../...Comes Around (Interlude)
                            ...                       
693                                  Enjoy the Silence
730                         Butterflies and Hurricanes
762                                            Islands
780                                              Intro
808                                        Crystalised
Name: track_name, Length: 85, dtype: object


In [40]:
di=df[df['album']=='Divide']['track_name']
print(di)

Series([], Name: track_name, dtype: object)


In [43]:
# Kiểm tra nếu 'divide' có trong các giá trị unique của cột 'album'
if 'Divide' in df['album'].unique():
    print("Album 'divide' có trong danh sách.")
else:
    print("Album 'divide' không có trong danh sách.")




Album 'divide' không có trong danh sách.


In [8]:
# độ dài tung bình
avearage_duration = df['duration_min'].mean()
print('Độ dài trung bình là: ',avearage_duration)
# điểm phổ biến trung bình
avearage_pop = df['popularity'].mean()
print('Điểm phổ trung bình là: ',avearage_pop)
# bài hát dài nhất:
longest_song=df.loc[df['duration_min'].idxmax()]["track_name"]
print(longest_song)
# bài hát ngắn nhất:
shortest_song=df.loc[df['duration_min'].idxmin()]["track_name"]
print(shortest_song)
# bài hát phổ biến nhất
popular_song=df.loc[df['popularity'].idxmax()]["track_name"]
print(popular_song)
# số nghệ sĩ
total_artist=df['artist'].nunique()
print("total artist: ",total_artist)

Độ dài trung bình là:  3.3185161666666665
Điểm phổ trung bình là:  56.669
Lost Boy
Bezos I
That’s So True
total artist:  526


In [9]:
# Nhóm theo artist và đếm số lượng bài hát của mỗi nghệ sĩ.
a = df.groupby('artist')['track_name'].count().sort_values(ascending=False)
print(a)
# Nhóm theo album và tính điểm phổ biến trung bình của từng album.
b=df.groupby('album')['popularity'].mean().sort_values(ascending=False)
print(b)

artist
The Weeknd       26
Taylor Swift     25
Avril Lavigne    21
Alan Walker      14
Selena Gomez     12
                 ..
ISAEV             1
IDER              1
Hyper VIPER       1
Home              1
✝✝✝ (Crosses)     1
Name: track_name, Length: 526, dtype: int64
album
The Secret of Us (Deluxe)                                  97.0
APT.                                                       96.0
Black Panther The Album Music From And Inspired By         95.0
The Idol Episode 4 (Music from the HBO Original Series)    93.0
AM                                                         93.0
                                                           ... 
Meltdown                                                    0.0
Monkey Business (International Version)                     0.0
Never Coming Back                                           0.0
No Gravity                                                  0.0
✝✝✝ (Crosses)                                               0.0
Name: popularity, L

In [10]:
# Sắp xếp các bài hát theo popularity giảm dần.
df_sorted =df.sort_values(by='popularity',ascending=False)
print(df_sorted[['track_name','popularity']].head(10))

                                         track_name  popularity
611                                  That’s So True          97
606                                            APT.          96
0                          All The Stars (with SZA)          95
771  One Of The Girls (with JENNIE, Lily Rose Depp)          93
484                                I Wanna Be Yours          93
615                                            blue          92
83                                           Yellow          92
628                                 Sweater Weather          92
743                                    Show Me Love          92
34                                     Cruel Summer          90


In [11]:
# Sắp xếp các bài hát theo release_date từ mới đến cũ.
df['release_date'] = pd.to_datetime(df['release_date'], format='mixed', errors='coerce')
df_sorted = df.sort_values(by='release_date', ascending=False)
print(df_sorted[['track_name', 'artist', 'release_date']].head(10))


                    track_name         artist release_date
826            Meet Me Halfway        Sandëro   2025-04-11
828          Where Are You Now  Nick Giardino   2025-04-04
845                      ALONE          NEWER   2025-04-04
829                The Monster        Gaullin   2025-03-28
847                  BANGALORE       Cesqeaux   2025-03-28
841        Boots On The Ground    Dillin Hoox   2025-03-28
821   MONTAGEM TOMADA - Slowed           MXZI   2025-03-21
851  More Than Ever (Umbrella)          LEDUC   2025-03-21
774                     Oxygen          Pixia   2025-03-21
630                    Anxiety        Doechii   2025-03-14


In [12]:
art=df.groupby('artist')['track_name'].nunique().sort_values(ascending=False)

print(art.head(5))

artist
Taylor Swift     25
The Weeknd       23
Avril Lavigne    20
Alan Walker      13
Selena Gomez     12
Name: track_name, dtype: int64


In [ ]:
# tiền xử lí dữ liệu
df = df.drop_duplicates()
df['release_date'] = pd.to_datetime(df['release_date'], format='mixed', errors='coerce')
df['release_year'] = df['release_date'].dt.year
df_2010s = df[(df['release_year'] >= 2010) & (df['release_year'] <= 2019)]
df['duration_sec'] = df['duration_min'] * 60


In [13]:
print(df.head(5))

                 track_name          artist  \
0  All The Stars (with SZA)  Kendrick Lamar   
1                   Starboy      The Weeknd   
2                  Señorita    Shawn Mendes   
3                Heat Waves   Glass Animals   
4           Let Me Love You        DJ Snake   

                                               album release_date  popularity  \
0  Black Panther The Album Music From And Inspire...   2018-02-09          95   
1                                            Starboy   2016-11-25          90   
2                                           Señorita   2019-06-21          80   
3                                          Dreamland   2020-08-07          87   
4                                             Encore   2016-08-05          87   

                                         spotify_url                      id  \
0  https://open.spotify.com/track/3GCdLUSnKSMJhs4...  3GCdLUSnKSMJhs4Tj6CV3s   
1  https://open.spotify.com/track/7MXVkk9YMctZqd1...  7MXVkk9YMctZqd1S